"""add human review tracking

Revision ID: 1bfe21341a0e
Revises: efe225a630c4
Create Date: 2026-09-13 17:35:09.693842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfe21341a0e'
down_revision: Union[str, None] = 'efe225a630c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('reviewed_by_human', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('images', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'reviewed_at')
    op.drop_column('images', 'reviewed_by_human')
    # ### end Alembic commands ###
