"""remove duplicate sha256 index

Revision ID: efe225a630c4
Revises: 955d5d5e6b12
Create Date: 2026-09-12 12:15:12.662539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe225a630c4'
down_revision: Union[str, None] = '955d5d5e6b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_images_sha256_lookup', table_name='images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_images_sha256_lookup', 'images', ['sha256'], unique=False)
    # ### end Alembic commands ###
